server:
  config_version:
    $import: "version.yaml#/version"
  domain: "local.home.Mydomain.net"
  port: 443
  show_root_index: false
  enable_api_docs: true
  login_title: "Armor"
  login_subtitle: "ARMOR Reliably Manages Online Resources"
  login_icon_class: "bi bi-cloud-download"
  login_icon_url: 
  login_primary_color: "#198754"
  oidc_button_style: "btn-outline-success"
  
  # Landing page customization (all optional)
  landing_title: "STARTcloud Armor"
  landing_subtitle: "ARMOR Reliably Manages Online Resources"
  landing_description: "This is a secured download site"
  landing_icon_class: "bi bi-shield-check"
  landing_icon_url:
  landing_primary_color: "#198754"
  support_email: "support@startcloud.com"

  # CORS configuration (like zoneweaver)
  cors:
    whitelist:
      - "https://armor.mydomain.com"
    allow_origin: true  # true=allow whitelist, false=deny all, "specific"=exact matching
    preflight_continue: true
    credentials: true

swagger:
  allow_full_key_retrieval: false
  allow_temp_key_generation: true
  temp_key_expiration_hours: 1

ssl:
  cert: /etc/letsencrypt/live/armor.mydomain.com/fullchain.pem
  key: /etc/letsencrypt/live/armor.mydomain.com/privkey.pem

database:
  dialect: "sqlite"
  storage: "/var/lib/armor/file-metadata.db"
  logging: false

logging:
  log_directory: "/var/log/armor"
  log_level: "info"
  max_file_size_mb: 10
  max_files: 5
  enable_rotation: true
  enable_compression: true
  compression_age_days: 7

authentication:
  jwt_secret: "__JWT_SECRET_FROM_FILE__"
  jwt_expiration: "24h"
  
  local:
    users:
    allowed_directories:
    static_directories:

  oidc_providers:

  permission_strategy: "domain_based"
  domain_mappings:
    downloads: ["*@Mydomain.net"]
    uploads: ["*@Mydomain.net"]
    delete: ["*@Mydomain.net"]
  
  claims_mappings:
    downloads:
      - claim: "groups"
        values: ["file-readers", "all-users"]
    uploads:
      - claim: "groups"
        values: ["file-admins"]
      - claim: "role"
        values: ["admin"]
