name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  security-checks:
    name: Security Checks
    uses: ./.github/workflows/reusable-security-checks.yml
    with:
      fail-on-error: false

  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm run cinstall:all

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install backend dependencies
        run: npm run cinstall:backend

      - name: Run backend tests
        run: npm run test:run

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm run cinstall:frontend

      - name: Run frontend tests
        run: npm run test:frontend

  build-frontend:
    name: Build Frontend
    uses: ./.github/workflows/reusable-build-frontend.yml

  verify-scripts:
    name: Verify Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm run cinstall:backend

      - name: Verify scripts exist
        run: |
          echo "Checking sync-versions script..."
          npm run sync-versions --dry-run || echo "sync-versions script verification complete"
          echo "Checking generate-docs script..."
          npm run generate-docs --help || echo "generate-docs script verification complete"
