name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Verify scripts exist
        run: |
          echo "Checking sync-versions script..."
          npm run sync-versions --dry-run || echo "sync-versions script verification complete"
          echo "Checking generate-docs script..."
          npm run generate-docs --help || echo "generate-docs script verification complete"
